=== rmemoria/datastream/src/main/resources/datastream-1.2.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="graphSchema" type="graphSchema"/>

    <xs:complexType name="property">
        <xs:sequence>
            <xs:element name="objectGraph" type="objectGraph" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="use" type="propertyUse"/>
        <xs:attribute name="elementName" type="xs:string"/>
        <xs:attribute name="xmlAttribute" type="xs:boolean"/>
        <xs:attribute name="customType" type="customType" />
        <xs:attribute name="includeNullValues" type="xs:boolean" use="optional" />
    </xs:complexType>

    <xs:complexType name="objectGraph">
        <xs:sequence>
            <xs:element name="property" type="property" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="class" type="xs:string" use="required"/>
        <xs:attribute name="parentProperty" type="xs:string"/>
        <xs:attribute name="ignorePropsNotDeclared" type="xs:boolean" use="optional"/>
        <xs:attribute name="customPropertiesNode" type="xs:string" use="optional"/>
        <xs:attribute name="includeNullValues" type="xs:boolean" use="optional" />
    </xs:complexType>

    <xs:complexType name="graphSchema">
        <xs:sequence>
            <xs:element name="objectGraph" type="objectGraph" minOccurs="0" maxOccurs="1"/>
            <xs:element name="objectCollection" type="objectCollection" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="objectCollection">
        <xs:sequence>
            <xs:element name="objectGraph" type="objectGraph"
                        minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="class" type="xs:string" />
    </xs:complexType>

    <xs:simpleType name="propertyUse">
        <xs:restriction base="xs:string">
            <xs:enumeration value="REQUIRED"/>
            <xs:enumeration value="IGNORE"/>
            <xs:enumeration value="NOT_REQUIRED"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="customType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="STRING"/>
            <xs:enumeration value="INT"/>
            <xs:enumeration value="LONG"/>
            <xs:enumeration value="DOUBLE"/>
            <xs:enumeration value="FLOAT"/>
            <xs:enumeration value="BOOLEAN"/>
            <xs:enumeration value="DATE"/>
            <xs:enumeration value="CHAR"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== rmemoria/datastream/src/test/resources/list-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<graphSchema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datastream-1.2.xsd">

    <objectGraph name="order" class="com.rmemoria.datastream.test.model.Order">
        <property name="id" xmlAttribute="true" use="REQUIRED"/>
        <property name="customer">
            <objectGraph name="customer" class="com.rmemoria.datastream.test.model.Customer">
                <property name="id" xmlAttribute="true" use="REQUIRED"/>
				<property name="orders" use="IGNORE" />
            </objectGraph>
        </property>
        <property name="items" >
            <objectGraph name="item" class="com.rmemoria.datastream.test.model.Item" parentProperty="order">
                <property name="product.id" elementName="product" xmlAttribute="true" />
                <property name="quantity" elementName="quantity" xmlAttribute="true" />
                <property name="unitPrice" elementName="unitPrice" xmlAttribute="true" />
            </objectGraph>
        </property>
    </objectGraph>

</graphSchema>

=== rmemoria/datastream/src/test/resources/null4-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<graphSchema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datastream-1.2.xsd">

    <objectGraph name="person" class="com.rmemoria.datastream.test.model.Person"
        includeNullValues="true" >
        <property name="name" />
        <property name="birthDate" />
        <property name="address.street" elementName="street" xmlAttribute="true" />
        <property name="address.zip" elementName="zip" xmlAttribute="true" />
        <property name="address.area" elementName="area" xmlAttribute="true" />
        <property name="address.number" elementName="number" xmlAttribute="true" use="REQUIRED"/>
    </objectGraph>

</graphSchema>
